nelmio_api_doc:
    documentation:
        servers:
            - url: '%env(APP_BASE_URL)%'
            - url: 'https://vytrvalec.uts.zcu.cz'
        info:
            title: Měsíční Vytrvalec
            description: Měsíční Vytrvalec
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        disable_default_routes: true
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
