framework:
    default_locale: cs_CZ
    translator:
        default_path: '%kernel.project_dir%/assets/translations'
        fallbacks:
            - cs_CZ
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
