apiVersion: apps/v1
kind: Ingress
metadata:
  name: vytrvalec-kts
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  tls:
    - hosts:
        - vytrvalec.kts.zcu.cz
      secretName: vytrvalec-kts-tls
  defaultBackend:
    service:
      name: vytrvalec-nginx
      port:
        number: 80
  rules:
    - host: vytrvalec.kts.zcu.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vytrvalec-nginx
                port:
                  number: 80
