apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vytrvalec-uts
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    # nginx.org/server-snippets: |
    #   location / {
    #       return 404;
    #   }
spec:
  tls:
    - hosts:
        - vytrvalec.uts.zcu.cz
      secretName: vytrvalec-uts-tls
  defaultBackend:
    service:
      name: vytrvalec-nginx
      port:
        number: 80
  rules:
    - host: vytrvalec.uts.zcu.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vytrvalec-nginx
                port:
                  number: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        root /var/www/vytrvalec/public;
        server_name vytrvalec.uts.zcu.cz;
        
        client_max_body_size 256M;
        
        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://client:3000;
            proxy_redirect off;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            proxy_intercept_errors on;

            proxy_busy_buffers_size 512k;
            proxy_buffers 4 512k;
            proxy_buffer_size 256k;
        }

        location /ws {
            proxy_pass http://127.0.0.1:1337;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location ~ ^/api/ {
            try_files $uri /index.php$is_args$args;
        }

        location /uploads/ {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;

            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }

        location @static {
          try_files $uri /index.html =502;
        }

        error_log /var/log/nginx/project_error.log warn;
        access_log /var/log/nginx/project_access.log;

        location = /404.html {
            internal;
        }

        location = /500.html {
            internal;
        }

        location = /502.html {
            internal;
        }

        location = /503.html {
            internal;
        }

        error_page 502 = /502.html;
        error_page 503 = /503.html;
        error_page 500 = /500.html;
        error_page 404 = /404.html;
    }
