apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:8.3.0
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: db

        - name: MYSQL_USER
          value: db

        - name: MYSQL_PASSWORD
          value: db

        - name: MYSQL_DATABASE
          value: db
        ports:
        - containerPort: 3306
          name: vytrvalec-db
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
spec:
  storageClassName: csi-rbd-synergia
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
