apiVersion: apps/v1
kind: Deployment
metadata:
  name: vytrvalec-nginx
spec:
  selector:
    matchLabels:
      app: vytrvalec-nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vytrvalec-nginx
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}

        - name: rmq-config
          emptyDir: {}

        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: upload-pv
          persistentVolumeClaim:
            claimName: upload-pv
        - name: rabbitmq-pv
          persistentVolumeClaim:
            claimName: rabbitmq-pv

      imagePullSecrets:
        - name: server-deploy-token

      containers:
      - name: vytrvalec-nginx
        imagePullPolicy: IfNotPresent
        image: nginx:1.25.4-alpine
        ports:
          - containerPort: 80

        volumeMounts:
          - name: shared-files
            mountPath: /var/www/vytrvalec

          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf

          - name: upload-pv
            mountPath: /var/www/vytrvalec/public/uploads

      - name: vytrvalec-rmq
        imagePullPolicy: IfNotPresent
        image: heidiks/rabbitmq-delayed-message-exchange:4.0.2-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          - name: RABBITMQ_DEFAULT_PASS
            value: guest
        ports:
          - containerPort: 5672
          - containerPort: 15672
        volumeMounts:
          - name: rabbitmq-pv
            mountPath: /var/lib/rabbitmq/

      - name: vytrvalec-web
        imagePullPolicy: Always
        image: ipmil.civ.zcu.cz:4567/kiv/vytrvalec-server/app:${CI_COMMIT_SHORT_SHA}
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/vytrvalec

          - name: upload-pv
            mountPath: /var/www/vytrvalec/public/uploads
        lifecycle:
          postStart:
            exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/vytrvalec && chown -R www-data:www-data /var/www/vytrvalec"]
---
apiVersion: v1
kind: Service
metadata:
  name: vytrvalec-nginx
spec:
  selector:
    app: vytrvalec-nginx
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pv
spec:
  storageClassName: csi-rbd-synergia
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: csi-rbd-synergia
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
