name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none
          tools: composer
        env:
          COMPOSER_ALLOW_SUPERUSER: 1

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Install FrankenPHP
        run: curl -fsSL https://frankenphp.dev/install.sh | sh && sudo mv ./frankenphp /usr/local/bin/

      - name: Setup project
        run: |
          just pre-init
          just init

      - name: Run Behat tests
        run: just test
